#! /usr/bin/sh

mkdir .build/
cp mystery/ .build/ -r
pip install -r requirements.txt --target .build/
python3 - << EOF
from glob import glob
from shutil import rmtree
for path in glob(".build/**/__pycache__/", recursive=True):
    rmtree(path)
EOF
python3 -m zipapp .build/ -o mystery.pyz -m "mystery.__main__:start" -p "/usr/bin/env python3" -c
rm -r .build
