#! /usr/bin/sh

if [ $1 = "pyz" ]
then
	# Build zip archive using zipapp.
	mkdir .cache/
	cp mystery/ .cache/ -r
	pip install -r requirements.txt --target .cache/ >> /dev/null
	# Pay attention to line 14: tab * 2 + space * 4
	python3 - <<- EOF
		from glob import glob
		from shutil import rmtree
		for path in glob(".cache/**/__pycache__/", recursive=True):
		    rmtree(path)
	EOF
	python3 -m zipapp .cache/ -o mystery.pyz -m "mystery.__main__:start" -p "/usr/bin/env python3" -c
	rm -r .cache
elif [ $1 = "exec" ]
then
	# Build executable file using pyinstaller.
	pyinstaller -D mystery/__main__.py -n mystery --additional-hooks-dir . -y
	rm -r build/ mystery.spec
else
	echo "Unknown action '$1'"
fi
